
CREATE TABLE Towns (
    Id INT IDENTITY NOT NULL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
)

CREATE TABLE Addresses (
    Id INT IDENTITY NOT NULL PRIMARY KEY,
    AddressText VARCHAR(500) NOT NULL,
    TownId INT NOT NULL FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE Departments (
    Id INT IDENTITY NOT NULL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL  
)

CREATE TABLE Employees (
    Id INT IDENTITY NOT NULL PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
    MiddleName VARCHAR(255) NOT NULL, 
    LastName VARCHAR(255) NOT NULL,
    JobTitle VARCHAR(255) NOT NULL, 
    DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Departments(Id),
    HireDate DATETIME NOT NULL,
    Salary FLOAT NOT NULL,
    AddressId INT NOT NULL FOREIGN KEY REFERENCES Addresses(Id)
)
