CREATE TABLE Passengers
(
    Id INT NOT NULL IDENTITY PRIMARY KEY,
    [Name] NVARCHAR(80) NOT NULL
)

CREATE TABLE Towns
(
    Id INT NOT NULL IDENTITY PRIMARY KEY,
    [Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE RailwayStations
(
    Id INT NOT NULL IDENTITY PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL,
    TownId INT NOT NULL FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE Trains
(
    Id INT NOT NULL IDENTITY PRIMARY KEY,
    HourOfDeparture NVARCHAR(5) NOT NULL,
    HourOfArrival NVARCHAR(5) NOT NULL,
    DepartureTownId INT NOT NULL FOREIGN KEY REFERENCES Towns(Id),
    ArrivalTownId INT NOT NULL FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE TrainsRailwayStations
(
    TrainId INT NOT NULL FOREIGN KEY REFERENCES Trains(Id),
    RailwayStationId INT NOT NULL FOREIGN KEY REFERENCES RailwayStations(Id)
    PRIMARY KEY(TrainId, RailwayStationId)
)

CREATE TABLE MaintenanceRecords
(
    Id INT NOT NULL IDENTITY PRIMARY KEY,
    DateOfMaintenance DATE NOT NULL,
    Details NVARCHAR(2000) NOT NULL,
    TrainId INT NOT NULL FOREIGN KEY REFERENCES Trains(Id)
)

CREATE TABLE Tickets
(
    Id INT NOT NULL IDENTITY PRIMARY KEY,
    Price DECIMAL(18, 2) NOT NULL,
    DateOfDeparture DATE NOT NULL,
    DateOfArrival DATE NOT NULL,
    TrainId INT NOT NULL FOREIGN KEY REFERENCES Trains(Id),
    PassengerId INT NOT NULL FOREIGN KEY REFERENCES Passengers(Id),
)